### ISSUE TITLE
Could not run the project based on the README information

### ISSUE THREAD

**Issue by kbirken** [IlyaYuskevich/diplomacy#6]
The project cannot be run out of the box (at least not on my system MacOS Ventura 13.4). 

When trying to run the docker command from the README, the env file `.env.local` is missing. I tried to copy the existing `.env.template`, but this resulted in a list of several Python errors.

**Comment by IlyaYuskevich** [comment]
Added explanations on creating Supabase instance to readme b3f978bca13e1de8a4f17c44d2d9937b39f02dd6
